### ISSUE TITLE
Could only see one commit

### ISSUE THREAD

**Issue by formulahendry** [leftstick/vscode-gitk#1]
Great extension. However, I could only see one commit somehow. (git version 1.9.5)

![image](https://cloud.githubusercontent.com/assets/1050213/25843914/7a08f35e-34db-11e7-8ef9-7d53ca5ff2df.png)

**Comment by leftstick** [comment]
It uses `git log --format="%h-=-%s-=-%an<%ae>-=-%ad" --date=iso src/platformio.ts` internally, can you check if it executed correctly in terminal?

**Comment by formulahendry** [comment]
They are the same. But after installing the v1.0.2, it works well now. 😄
