### ISSUE TITLE
Extra line breaks after coloured lines in detail view

### ISSUE THREAD

**Issue by evilquinn** [leftstick/vscode-gitk#10]
Hey, excellent extension, thanks.

In my client, there appeared to be extra line breaks in the detail output.

Here's raw output on a terminal:
![image](https://user-images.githubusercontent.com/5812068/164337462-797e5799-56d5-44fb-b782-97c9194ace80.png)

And here's a view of the detail output for the same commit:
![image](https://user-images.githubusercontent.com/5812068/164337708-84fb51f2-2956-41d2-b24d-6eac90dbc82d.png)

Snapshot of the raw html:
![image](https://user-images.githubusercontent.com/5812068/164338093-b8d035bd-f3a0-44ca-aa93-1a8019403272.png)

**Comment by evilquinn** [comment]
think it's down to an extra `\n` being added during colouring of changed lines here:
https://github.com/leftstick/vscode-gitk/blob/d466cc8540cbb683b6de63c0dfde9350d2c1fd84/src/services/gitLogResolver.ts#L77-L78

**Comment by evilquinn** [comment]
question: is this a feature? and not a defect?

I ask because this appears to have been the case since the first commit here, and the demo gif in the readme shows these extra breaks...

**Comment by leftstick** [comment]
Hi @evilquinn  thanks for your questions, i don't think it is a feature. 
@geforcesong  would you please check it? Thanks

**Comment by evilquinn** [comment]
fixed by https://github.com/leftstick/vscode-gitk/pull/11
thanks!

**Comment by leftstick** [comment]
@evilquinn already published to martketplace, thanks for your awesome work

**Comment by evilquinn** [comment]
unbelievable!
great stuff everyone, thank you!.


(if of interest, my first _ever_ pull-request to someone else's github project! feels good)
