### ISSUE TITLE
using vscode's default font?

### ISSUE THREAD

**Issue by beeplin** [leftstick/vscode-gitk#2]
wonderful tool!

Only a small issue: the font is not the vscode's default font, and cannot be reset.

**Comment by leftstick** [comment]
Yes, you are right, i gave a monospaced font for pretty look, once using default font, it looks like:

![screen shot 2017-05-25 at 2 20 31 pm](https://cloud.githubusercontent.com/assets/1059956/26438456/ba405cf6-4155-11e7-89c7-87c84a6b0990.png)


I will consider giving an option to reset font on user's need. Thanks for your feedback

**Comment by beeplin** [comment]
there are many choices of monospaced fonts, such as consolas etc. :)

**Comment by leftstick** [comment]
Sure, give a try `1.2.0`, new configuration item `gitk.fontFamily` added

**Comment by beeplin** [comment]
nice~!
![image](https://cloud.githubusercontent.com/assets/13058150/26451947/a3d77036-4190-11e7-9a87-8c299f5ea28e.png)

The upper screen is all bold-font, which might be a little bit hard to read. Consider use normal font instead of bold?

**Comment by leftstick** [comment]
Only `selected` line was applied with bold, check below:

![screen shot 2017-05-26 at 1 12 08 pm](https://cloud.githubusercontent.com/assets/1059956/26481666/507fd3bc-4215-11e7-91ca-b2a0d38406ac.png)

Are you using some customized `fontFamily`?
