### ISSUE TITLE
git is not recognized as an internal or external command

### ISSUE THREAD

**Issue by muthukumar143** [leftstick/vscode-gitk#4]
I already have a git installed on my 
![screenshot 54](https://user-images.githubusercontent.com/25875778/50482437-8e9c3d00-0a0c-11e9-9bd8-481e0545d3bc.png)
machine. However i see this message.

**Comment by Toon34** [comment]
Hi !

I had same problem and -> https://stackoverflow.com/questions/4492979/git-is-not-recognized-as-an-internal-or-external-command?answertab=votes#tab-top
Now, it's working !

**Comment by leftstick** [comment]
@Toon34 thanks
