### ISSUE TITLE
Change colours in gitk view

### ISSUE THREAD

**Issue by Rah1x** [leftstick/vscode-gitk#8]
Hi,

Is it possible for you to add some feature that allows us to change the colours used in gitk instead of the default red/green? 

Thanks

**Comment by leftstick** [comment]
@geforcesong would you please take a look at this feature request?

**Comment by geforcesong** [comment]
I added some color config for the top part. You can add some settings in your vscode user settings. don't know if this is what your want.
e.g. in your user settings.json
{...
"gitk": {
        "colors": {
            "hash": "red",
            "message": "blue",
            "author": "orange",
            "date": "white"
        }
    }
...}

**Comment by Rah1x** [comment]
awesome.. did you publish the changes yet? It says this atm:

![image](https://user-images.githubusercontent.com/841857/71132666-3deca800-224c-11ea-95eb-267a60dcfd27.png)

**Comment by Rah1x** [comment]
Also, can we change the default text colour? Im using VSCode in dark mode and the default white is too sharp

**Comment by geforcesong** [comment]
added "defaultDetail" color, that can change the default color in detail section.
I have pushed code, need re-publish again.
@leftstick

**Comment by Rah1x** [comment]
I think you are not doing `VSCE Publish` correctly as the last publish was on 4/18/2019 at
https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-gitk

**Comment by geforcesong** [comment]
You are right, need my boss @leftstick to publish, i can't do that.

**Comment by leftstick** [comment]
sorry guys, i am in hospital taking care of my child. I will publish the new enhancem ent while i get time.

**Comment by leftstick** [comment]
@Rah1x released
